/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentCodeRouteImport } from './routes/agent-code'
import { Route as MimicRouteImport } from './routes/mimic'
import { Route as ApiAgentStatusRouteImport } from './routes/api/agent-status'
import { Route as ApiAgentStreamRouteImport } from './routes/api/agent-stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCodeRoute = AgentCodeRouteImport.update({
  id: '/agent-code',
  path: '/agent-code',
  getParentRoute: () => rootRouteImport,
} as any)
const MimicRoute = MimicRouteImport.update({
  id: '/mimic',
  path: '/mimic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStatusRoute = ApiAgentStatusRouteImport.update({
  id: '/api/agent-status',
  path: '/api/agent-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStreamRoute = ApiAgentStreamRouteImport.update({
  id: '/api/agent-stream',
  path: '/api/agent-stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent-code': typeof AgentCodeRoute
  '/mimic': typeof MimicRoute
  '/api/agent-status': typeof ApiAgentStatusRoute
  '/api/agent-stream': typeof ApiAgentStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent-code': typeof AgentCodeRoute
  '/mimic': typeof MimicRoute
  '/api/agent-status': typeof ApiAgentStatusRoute
  '/api/agent-stream': typeof ApiAgentStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent-code': typeof AgentCodeRoute
  '/mimic': typeof MimicRoute
  '/api/agent-status': typeof ApiAgentStatusRoute
  '/api/agent-stream': typeof ApiAgentStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent-code'
    | '/mimic'
    | '/api/agent-status'
    | '/api/agent-stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agent-code'
    | '/mimic'
    | '/api/agent-status'
    | '/api/agent-stream'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent-code'
    | '/mimic'
    | '/api/agent-status'
    | '/api/agent-stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentCodeRoute: typeof AgentCodeRoute
  MimicRoute: typeof MimicRoute
  ApiAgentStatusRoute: typeof ApiAgentStatusRoute
  ApiAgentStreamRoute: typeof ApiAgentStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-code': {
      id: '/agent-code'
      path: '/agent-code'
      fullPath: '/agent-code'
      preLoaderRoute: typeof AgentCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mimic': {
      id: '/mimic'
      path: '/mimic'
      fullPath: '/mimic'
      preLoaderRoute: typeof MimicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-status': {
      id: '/api/agent-status'
      path: '/api/agent-status'
      fullPath: '/api/agent-status'
      preLoaderRoute: typeof ApiAgentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-stream': {
      id: '/api/agent-stream'
      path: '/api/agent-stream'
      fullPath: '/api/agent-stream'
      preLoaderRoute: typeof ApiAgentStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentCodeRoute: AgentCodeRoute,
  MimicRoute: MimicRoute,
  ApiAgentStatusRoute: ApiAgentStatusRoute,
  ApiAgentStreamRoute: ApiAgentStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
